version: '3'
services:

  tweet_collector:
    container_name: tweet_collector
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
    - 27017:27017

  postgresdb:
    container_name: postgresdb
    image: postgres
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres

  etl_job:
    container_name: etl_job
    build: etl_job/
    volumes:
    - ./etl_job/:/app

  slack_bot:
    container_name: slack_bot
    build: slack_bot/
    volumes:
    - ./slack_bot/:/app